name: 自动同步Fork上游仓库
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v5
        with:
          token: ${{secrets.SYNC_TOKEN}} # 20260817因同步出错，增加PAT权限
          fetch-depth: 0

      - name: 配置Git用户
        run: |
          git config --global user.name "github‑actions[bot]"
          git config --global user.email "actions@github.com"
      
      - name: 重置上游仓库
        run: |
          git remote remove upstream || true
          git remote add upstream https://github.com/HKUDS/DeepTutor.git

      - name: 获取全部远程分支
        run: git fetch --all

      # 同步 main
      - name: 更新main分支
        run: |
          git checkout main
          git pull origin main --rebase || true  # 20260817因同步出错，增加分支合并最新逻辑
          # git merge upstream/main              # 此改为下一行，对应上一行的修改
          git merge upstream/main --no-edit || true
          git push origin main

      # 同步 dev，强制指定本地分支，消除分支名歧义
      - name: 更新dev分支
        run: |
          # git checkout origin/dev -b dev || git checkout dev
          # git merge upstream/dev
          # git push origin dev
          # 20260817因同步出错，跟main分支一样，dev分支也优化更新逻辑如下
          git checkout --track origin/dev || git checkout dev
          git pull origin dev --rebase || true
          git merge upstream/dev --no-edit || true
          git push origin dev
          
